### PR TITLE
CQRSlite with async functionality

### PR DESCRIPTION
**Pull request by seano288**
I use CQRSlite in some of my own projects and needed async functionality. I thought I'd submit a PR in case you would like to include it. I've tried to add full test coverage of my changes.

### CODE REVIEW

**Comment by gautema** [comment]
Cool. I'll take a look at it in a bit.

**Comment by dsincl12** [comment]
*bump*

I hope you haven't forgotten about this pull request :) It would be awesome to have async support in CQRSlite.

**Comment by gautema** [comment]
I haven't forgotten it, I'm just considering some options. I would like an async api, but don't want to maintain both a sync and an async one, so ideally I want to make the whole thing async, without making to many breaking changes.

**Comment by gautema** [comment]
New version with async api is released now.

**Pull request closed without merging**
