### PR TITLE
.Net Core port

### PR DESCRIPTION
**Pull request by al222cv**
Hi!

I have made a port of CQRSlite to work with .Net Core for my own projects, so if you found it useful, heres a PR of it.

Some minor changes had to be made:

- XUnit is used instead of NUnit (no support) as test framework 
- Caching has changed in .Net Core, so some changes for those stuffs
- Some minor changes in reflections in .Net Core caused some small changes
- Sample Web project changed to a ASP.Net Core Web Application

### CODE REVIEW

**Comment by gautema** [comment]
Nice work. I will probably let the PR be until the Core RTM is released in a week, to see what happens to project.json and if theres anything else that might need change.

**Comment by al222cv** [comment]
Thanks, and that sounds like a good plan!

**Comment by al222cv** [comment]
Seems like project.json is still there even in 1.0.0, so i have updated to 1.0.0 in the project.json files.

**Comment by CumpsD** [comment]
Would be nice to see this in, maybe update to 1.0.1 and merge?

**Comment by souzara** [comment]
I know that you(@al222cv) is porting, anyway I did the same, if  it helps,  I published a beta version in 
[beta version](https://github.com/souzara/CQRSLite-NetCore-Beta)
#5

**Comment by gautema** [comment]
I haven't been on the ball with this upgrade lately, but would really like to see a core version. I don't work with .NET Core myself, so I'm not very updated on it. So there's a few things that keeps me from merging:

- Is it possible to reference a .NET Core project from regular .NET, so only one version needs to be maintained?
- My appveyor build won't build the project and run the tests. If anyone has the time to help with this, it would be appreciated

**Comment by CumpsD** [comment]
It should be possible to reference a .NET core project, see http://www.michael-whelan.net/porting-dotnet-framework-library-to-dotnet-core/ (Add target frameworks to project.json file)

**Comment by luisrudge** [comment]
Hey, I want to use this with .net core, but I'm not sure where we are with this PR. What do you need in order to merge this and publish a new package? I'll be helping you in any way I can.

**Comment by luisrudge** [comment]
ping @gautema @al222cv

**Comment by AlexZeitler** [comment]
I would be highly interested as well...

**Comment by gautema** [comment]
Finally it's merged and published. Please try it out and report any problems.

**Comment by luisrudge** [comment]
@gautema is this on nuget yet?

**Comment by gautema** [comment]
@luisrudge Yes.

**Comment by luisrudge** [comment]
Awesome, thanks!

**Pull request merged**
