### PR TITLE
Add AspNetCore extensions

### PR DESCRIPTION
**Pull request by sbiaudet**
In reply to issue #42

### CODE REVIEW

**Comment by gautema** [comment]
I think I'll have to think a bit about this change. While I do like the idea, I don't want to maintain another nuget package, and don't want to the regular package to have a dependency on AspNetCore. It also makes it a bit harder to figure how to actually set everything up, but it defiantly makes the code cleaner...

**Comment by sbiaudet** [comment]
I understand. Put reference directly in core project is not a good idea. But having different packages is not a problem for me. For example you have lot of package for aspnetcore. It's easier to maintain, test...

But if you want we could make an other repo for extensions with the name CQRSLIte.Extensions

**Comment by Soarc** [comment]
Nice job @sbiaudet ! I was doing exactly same thing when found your accurate implementation! One small tip: it is good to place aspnetcore extension methods in Microsoft.Extensions.DependencyInjection namespace. This is done for all popular aspnetcore libs.

**Comment by Soarc** [comment]
BTW @sbiaudet , you can avoid AspNetCore dependency. The only thing used is IApplicationBuilder. You can define your interface like ILoggerFactory and inject it into aspnetcore's configure method.
`
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, ICqrsLiteFactory cqrsFactory)
        {
cqrsFactory.UseCQRSLiteBus(...);
`
But still you need "Microsoft.Extensions.DependencyInjection" dependency.

**Comment by Rabosa616** [comment]
Are you plan to integrate this?
Would be awesome!

**Comment by gautema** [comment]
I don't have any plans to add this in it's current form. I don't want the extra dependencies and the connection to asp.net core or at least Microsoft.Extensions.DependencyInjection in the library and don't want to maintain another package with this very limited functionality in it.

**Comment by bdongus** [comment]
@sbiaudet Why don't you create an addon. A seperate integration package. @gautema  woudln't have to maintain another package and the people have a a nice integration to aspnetcore if they want to.

**Pull request closed without merging**
