### PR TITLE
Routes marked protected for the sake of sake Router extensibility

### PR DESCRIPTION
**Pull request by managerger**
Need ability to extend Router somehow

### CODE REVIEW

**Comment by gautema** [comment]
Hi. 

Can you tell a bit more about the use case for this change? Why do you need to override its methods, and not implement it again (it is only 15 lines of code) or make a decorator for it?

**Comment by managerger** [comment]
Hi

I'd like to add the next logic to event Publish -> if any event handler fails, then wrap it to the job (quartz, hangfire whatever) in order to get event handler eventually done. Therefore, I need to re-implement `IEventPublisher` (seems like a right place to do that), but if I do, then I don't have an access to `_routes` since it is privet.
To get the goal I need to re-implement all the interfaces.

**Comment by managerger** [comment]
Any updates on this? 
Let me know if you need something in order to proceed. Thanks)

**Comment by gautema** [comment]
Hi. I’ve been a bit busy before Christmas and I’m traveling for a week now,
so I haven’t had much time. But I will take a better look when I get home
early January.

**Comment by managerger** [comment]
Hey! How is it going? Have you had a chance to take a closer look at these minor changes?
Thanks)

**Comment by gautema** [comment]
Hi. After thinking long and hard about it, I have decided not to implement these changes. The changes might not be big, but it sets precedence for the whole project to make everything protected. I think  a better solution is just to copy and change the file in question.

**Pull request closed without merging**
